project:
  type: website
  output-dir: docs
  
website:
  title: "NGS Bioinformatics course"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - text: Modules
        menu:
          - href: course_modules/Module1/module1.qmd
            text: "File formats"
          - href: course_modules/Module2/module2.qmd
            text: "Reads alignment"
          - href: course_modules/Module3/module3.qmd
            text: "Variant calling"
          - href: course_modules/Module4/module4.qmd
            text: "Structural Variation Calling"
          - href: course_modules/Module5/module5.qmd
            text: "Genome assembly"
          - href: course_modules/Module6/module6.qmd
            text: "RNA-seq"
          - href: course_modules/Module7/module7.qmd
            text: "CHiP-Seq"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "File formats"
        contents:
          - course_modules/Module1/module1_manual.qmd
          - course_modules/Module1/module1_exercises.qmd
      - section: "Read alignment"
        contents:
          - course_modules/Module2/module2_manual.qmd
          - course_modules/Module2/module2_exercises.qmd
      - section: "Variant calling"
        contents:
          - course_modules/Module3/module3_manual.qmd
          - course_modules/Module3/module3_exercises.qmd
      - section: "Structural Variation Calling"
        contents:
          - course_modules/Module4/module4_manual.qmd
          - course_modules/Module4/module4_exercises.qmd
      - section: "Genome Assembly"
        contents:
          - course_modules/Module5/module5_manual.qmd
          - course_modules/Module5/module5_exercises.qmd
      - section: "RNA-Seq"
        contents:
          - course_modules/Module6/module6_manual.qmd
          - course_modules/Module6/module6_exercises.qmd
      - section: "CHiP-Seq"
        contents:
          - course_modules/Module7/module7_manual.qmd
          - course_modules/Module7/module7_exercises.qmd
            

  page-navigation: true 
  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 
  search:
    location: navbar
    type: textbox

output:
  html_document:
    highlight: pygments
    css: "_extensions/styles.css"
    toc: true
    toc_float:
      collapsed: false
    includes:
      after_body: _extensions/footer.html
      

format:
  html:
    theme:
      light: [theme_lter-edu-light, _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss]
      dark: [theme_lter-edu-dark, _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss]
    anchor-sections: true
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true
