---
title: "Acknowledgements"
format: html
---

As included in ANSI/NISO Z39.104-2022, CRediT, Contributor Roles Taxonomy <https://www.niso.org/publications/z39104-2022-credit>

### Contributor Roles

-   **Conceptualization**

    (Ideas; formulation or evolution of overarching research goals and aims.)

-   **Data curation**

    (Management activities to annotate (produce metadata), scrub data and maintain research data (including software code, where it is necessary for interpreting the data itself) for initial use and later re-use.)

-   **Formal analysis**

    (Application of statistical, mathematical, computational, or other formal techniques to analyze or synthesize study data.)

-   **Methodology**

    (Development or design of methodology; creation of models)

-   **Resources**

    (Provision of study materials, reagents, materials, patients, laboratory samples, animals, instrumentation, computing resources, or other analysis tools.)

-   **Supervision**

    (Oversight and leadership responsibility for the research activity planning and execution, including mentorship external to the core team)

-   **Validation**

    (Verification, whether as a part of the activity or separate, of the overall replication/reproducibility of results/experiments and other research outputs. )

-   **Visualization**

    (Preparation, creation and/or presentation of the published work, specifically visualization/data presentation)

© Wellcome Connecting Science
