---
title: "Introduction"
---

## **Overview of adult learning principles and training design techniques**

**What this module covers:**

This introductory module gives you a chance to explore your own memories and habits regarding learning and training. 

It also explains educational theory that underpins adult teaching and training.

**Intended learning outcomes** for this module:

-   List main principles underpinning adult learning 

-   Describe practical application of adult learning principles 

-   Explain outcome driven design approach for use in training and teaching 

-   Define learning outcomes in a SMART way using Bloom's taxonomy

-   Discuss purpose, scope and types of evaluation in education

This module takes approximately 2 hours to go through.

#### **Reflection: What are your learning and teaching experiences?**

Recall

-   Your happiest memory of learning.

-   What experience they remember as being most fun, most effective, and perhaps most influential?

-   You happiest memory of teaching or training.

-   What experience do you remember as being most fun, most effective, and perhaps most influential ?

-   Do you teach or train the way you like to learn? Why? or Why not?
