---
title: "Overview"
format: html
---

# Module Title

Genome Assembly

# Authors

This tutorial was written by Jacqui Keane based on material from Shane McCarthy and Thomas Otto.

# Duration

3 hours

# Key topics

# Learning outcomes

On completion of the tutorial, you can expect to be able to:

• Describe the different approaches to genome assembly

• Generate a genome assembly from Illumina data

• Generate a genome assembly from PacBio data

• Generate statistics to evaluate the quality of a genome assembly

• Estimate the size of a genome assembly

# Activities

-   Lecture: 1 hour

-   Practical exercises: 1.5 hours

-   Assessment quiz: 0.5 hours

# Manual

[Module manual](module5_manual.qmd)

[Exercises](module5_exercises.qmd)

[Solutions](module5_solutions.qmd)

# Presentation slides

(PPT/PDF, to be generated from the module manual. Instructions on how to that will be added here.)

# Lecture recording, notes and scripts

# Check you knowledge quiz

[Questions](module5_assessment.qmd)

# Summary of this module

# Teaching guidance

[Instructor notes](module5_instructor_notes.qmd)

# Datasets

Practice files for this module can be found on [Github](https://github.com/WCSCourses/Precourses_DataRepo/tree/main/course_data_2025/linux_googlecolab_data).

# Platform Guidance

[Guide](module5_platform_guidance.qmd)
